"""Cambié el tipo de dato a los precios

Revision ID: 1f2d31650a05
Revises: 21da9f445d7e
Create Date: 2024-12-04 18:41:59.588836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2d31650a05'
down_revision = '21da9f445d7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
