"""Agregúe campo max_stock

Revision ID: 21da9f445d7e
Revises: b50beddfca58
Create Date: 2024-12-03 00:14:38.320603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21da9f445d7e'
down_revision = 'b50beddfca58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Product', sa.Column('max_stock', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Product', 'max_stock')
    # ### end Alembic commands ###
