"""Init

Revision ID: 3cb25a110e68
Revises: 1f2d31650a05
Create Date: 2024-12-04 18:46:33.821739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cb25a110e68'
down_revision = '1f2d31650a05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
