"""Add isActive Category

Revision ID: b50beddfca58
Revises: 139d30fa2b38
Create Date: 2024-11-29 20:50:48.107125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50beddfca58'
down_revision = '139d30fa2b38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Category', sa.Column('isActive', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Category', 'isActive')
    # ### end Alembic commands ###
